## Settings
title: RamHacks
owner: ""
url: "https://rhodyra.ms"
baseurl: "/"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: "ramhacks@etal.uri.edu"
github: "ramhacks"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "RAM Hacks, URI CS"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "Î±Î²Î³Î´ÎµÎ¶Î·Î¸Î¹ÎºÎ»Î¼Î½Î¾Î¿Ï€ÏÏƒÏ„Ï…Ï†Ï‡ÏˆÏ‰âˆ·âˆ«âˆ®âˆâˆâˆ§âˆ¨âˆ‘âˆâˆªâˆ©âˆˆâˆµâˆ´âŠ¥â€–âˆ âŒ’âŠ™â‰ŒâˆšğŸ•"
